
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbazrwpujinrkjstkloi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiYXpyd3B1amlucmtqc3RrbG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTEwMDcsImV4cCI6MjA2MTM2NzAwN30.7DNOXMo_zm2x3KAn14L3fJdq-1Ff3IRuXPxNO1xElME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
